# Generated by Django 4.2.5 on 2023-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PushRevelations', '0002_remove_gallery_image_revelation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revelation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
