# Generated by Django 4.2.5 on 2023-10-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PushRevelations', '0003_revelation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revelation',
            name='slug',
        ),
    ]
