# Generated by Django 4.2.5 on 2023-10-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PushRevelations', '0004_remove_revelation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revelation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
