# Generated by Django 4.2.5 on 2023-10-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0014_alter_category_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=models.ImageField(upload_to='Catalog\\static\\images\\images\\category_avatars'),
        ),
    ]
