# Generated by Django 4.2.5 on 2023-11-13 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PushRevelations', '0005_alter_revelation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevelationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('revelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PushRevelations.revelation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revelation_answers', to=settings.AUTH_USER_MODEL)),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_revelation_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
